apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.2.0
    helm:
      releaseName: external-dns
      valuesObject:
        provider: digitalocean

        digitalocean:
          apiToken: dop_v1_0ad051c6daabfafc82509a868cff5e464e8a1359998c0c85952ecdcce0be6ecd

        interval: "1m"

        policy: sync # or upsert-only

        # domainFilters: [ 'your_domain' ]
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns

