apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.3
    helm:
      releaseName: metallb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.40.40.10-10.40.40.10

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2advertisement
  namespace: metallb-system