apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.12
    helm:
      releaseName: external-secrets
      valuesObject:

  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

#---
#apiVersion: external-secrets.io/v1beta1
#kind: ClusterSecretStore
#metadata:
#  name: vault-backend
#spec:
#  provider:
#    vault:
#      server: "https://vault.staging.mirafzal.uz"
#      path: "kv"
#      version: "v2"
#      auth:
#        tokenSecretRef:
#          name: "vault-token"
#          key: "token"
#          namespace: external-secrets

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: vault-token
#data:
#  token: cm9vdA== # "root"