apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.9.1
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          allowSnippetAnnotations: true
          ingressClassResource:
            default: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx